import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "iplay music App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className="h-[100vh]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
